### PR TITLE
Allow HTTP clients to be configured for auth and reply requests

### PR DESCRIPTION
**Pull request by bmorton**
Hey!  I've been looking into wrapping OpenTelemetry instrumentation around this library, but I need to be able to configure the `http.Client` instance used for this to be possible.  I'd also like to be able to configure timeouts for these requests, which this PR would also make possible.

**UPDATE:**
I've taken a second pass here and have this funneled through the configuration.  I am instrumenting this using [otelhttp](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/net/http/otelhttp).  I also had to change some interfaces to pass `context.Context` around to the right places to keep the span intact.

Using this PR looks something like this:

```go
instrumentedClient := &http.Client{
	Timeout: 15 * time.Second,
	Transport: otelhttp.NewTransport(http.DefaultTransport),
}

setting := core.AdapterSetting{
	AppID:       appID,
	AppPassword: appPassword,
	AuthClient:  instrumentedClient,
	ReplyClient: instrumentedClient,
}

adapter, err := core.NewBotAdapter(setting)
if err != nil {
	panic(err)
}
```

Which will produce events that look like this in a fully configured span:
trace-sample

### CODE REVIEW

**Comment by bmorton** [comment]
I suppose this still needs a way to funnel this configuration through from `core.NewBotAdapter()`.  That seems a bit trickier and I'll have to think on that a bit more.

**Comment by bmorton** [comment]
Hey @PrasadG193!  I've updated this PR to allow clients to be passed in and to properly pass context around to the places where it's needed for instrumentation.   I haven't added any additional test coverage yet, so I'd love some advise on if I should add some coverage around this.  It is largely backwards compatible, but the interface does change because we require the context to be passed in now.

**Review by PrasadG193 — APPROVED** [review]

**Comment by sahil-lakhwani** [comment]
hey @bmorton , I'm not totally sure, but will there be a changes required in the [examples](https://github.com/infracloudio/msbotbuilder-go/tree/develop/samples) as well?

**Comment by bmorton** [comment]
> hey @bmorton , I'm not totally sure, but will there be a changes required in the [examples](https://github.com/infracloudio/msbotbuilder-go/tree/develop/samples) as well?

@sahil-lakhwani , the interfaces I changed appear to be internal to the library and I don't see that it'd be used externally.  The interface that is used in the examples (and that I use within my service that uses this library) is the [`core.Adapter` interface](https://github.com/infracloudio/msbotbuilder-go/blob/develop/core/bot_framework_adapter.go#L36-L42), which already has `context.Context` included, I just continued passing it further into the call chain.  This also didn't need any changes in my app, so I expect there isn't anything breaking unless people are relying on the `activity.Response` or `client.Client` interfaces -- but both those seem mostly internal to me.

I think we should be good there!

**Comment by bmorton** [comment]
I'm happy to add some documentation for this somewhere too if you point me to where you think I should put it.  I think this should be useful for others too!

**Comment by sahil-lakhwani** [comment]
> > hey @bmorton , I'm not totally sure, but will there be a changes required in the [examples](https://github.com/infracloudio/msbotbuilder-go/tree/develop/samples) as well?
> 
> @sahil-lakhwani , the interfaces I changed appear to be internal to the library and I don't see that it'd be used externally. The interface that is used in the examples (and that I use within my service that uses this library) is the [`core.Adapter` interface](https://github.com/infracloudio/msbotbuilder-go/blob/develop/core/bot_framework_adapter.go#L36-L42), which already has `context.Context` included, I just continued passing it further into the call chain. This also didn't need any changes in my app, so I expect there isn't anything breaking unless people are relying on the `activity.Response` or `client.Client` interfaces -- but both those seem mostly internal to me.
> 
> I think we should be good there!

ok, sounds good, thanks @bmorton

**Review by sahil-lakhwani — APPROVED** [review]

**Pull request merged**
