### PR TITLE
Fixed conversation update activity handler failing with infinite loop #47

### PR DESCRIPTION
**Pull request by coupa-sbawaskar**
Please refer to issue #47 for details.

### CODE REVIEW

**Review by PrasadG193 — APPROVED** [review]

**Comment by PrasadG193** [comment]
Thanks for the PR @coupa-sbawaskar :pray:

**Comment by PrasadG193** [comment]
Please use develop as a base branch

**Comment by coupa-sbawaskar** [comment]
> Please use develop as a base branch

When can we expect this bug fix to be released?

**Comment by PrasadG193** [comment]
@coupa-sbawaskar We wanted to address this https://github.com/infracloudio/msbotbuilder-go/issues/46 before the next release. But if we couldn't do it, we can make a minor release in the early next week.

**Comment by coupa-sbawaskar** [comment]
> @coupa-sbawaskar We wanted to address this #46 before the next release. But if we couldn't do it, we can make a minor release in the early next week.

Created https://github.com/infracloudio/msbotbuilder-go/pull/49 for this. Please check and let me know.

**Comment by coupa-sbawaskar** [comment]
> @coupa-sbawaskar We wanted to address this #46 before the next release. But if we couldn't do it, we can make a minor release in the early next week.

@PrasadG193 , we need to release this issue as soon as possible. I am blocked on this. Please do the needful.

**Pull request merged**
